Rewrite Task of listening Stellar Messages (#545)
* add logs; change log level

* adding started logs for each task

* changing debug logs to info

* reduce restart interval

* revert to debug the other logs

* make listen() async; use tokio::select

* first iteration

* fix  the trait bound `service::Error<error::Error>: From<service::Error<oracle::errors::Error>>` is not satisfied
       --> clients/vault/src/system.rs:820:4

* cleanup clones; add names to threads

* add a precheck signal

* reduce timeouts; write log every 2 minutes

* update config and remove precheck when listening for stellar messages

* log every minute

* cleanup

* reduce timeout by moving it out to `poll_messages_from_stellar()`

* fix https://github.com/pendulum-chain/spacewalk/actions/runs/10369361893/job/28704943452?pr=545

OracleAgent is now `Arc<RwLock<>>`, since the message_sender is updated late in the code; inside the `listen_for_stellar_messages`

* move checking of proof building inside `fn start_oracle_agent()` for integration tests

* rebase

* https://github.com/pendulum-chain/spacewalk/actions/runs/10724299988/job/29739630347?pr=545#step:13:1938

* await before performing a compare

* update test config, and add `ntest` for long-running test cases

* use ubuntu 20, instead of the latest 22

* remove tokio spawns on archives; add ntest

* switch to ubuntu-latest

* add ntest to all test cases

* set timeout to 5 minutes

* free up disk space

* Use random secret for connecting to overlay in integration tests

* Run `cargo +nightly-2024-02-09 fmt --all`

* Remove ntest timeouts

* Add fallback to default stroop fee

* Reduce amount in redeem test

* Fix compilation error

* move `is_proof_building_ready` out of oracle agent

* run release

* use `try_recv` instead
https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761456867

https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761489738

https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761547893

https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761548974

* use `try_recv` instead
https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761456867

https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761489738

https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761547893

https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761548974

* https://github.com/pendulum-chain/spacewalk/actions/runs/11120883420/job/30898768243?pr=545

* https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1761484283,

https://github.com/pendulum-chain/spacewalk/actions/runs/11127602452/job/30920300244?pr=545

* clean testing issues

* fix issues

* https://github.com/pendulum-chain/spacewalk/actions/runs/11139347479/job/30962886547?pr=545#step:13:565

* remove env_logger

* fix fmt and clippy issues

* fix nightly issues

* remove 2nd declaration of agent

* https://github.com/pendulum-chain/spacewalk/actions/runs/11175397072/job/31066682184?pr=545

* fix timeout issue
https://github.com/pendulum-chain/spacewalk/actions/runs/11176052005/job/31071234041?pr=545#step:4:5765

* remove env_logger

* remove env_logger; move console-subscribe to dev-dependencies; remove useless script

* reduce changes

* cargo fmt and clippy

* https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1791591783

* remove unnecessary dependencies

* fix "the `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files."

* https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1795738055

* address major comments

* run cargo fmt

* remove `unwrap()`s

* https://github.com/pendulum-chain/spacewalk/pull/545#discussion_r1802855387,
https://github.com/pendulum-chain/spacewalk/pull/545/files#r1794072004

* https://github.com/pendulum-chain/spacewalk/actions/runs/11364931112/job/31813445329?pr=545

* use latest commit version

* use `.expect()` since this is only for test feature

---------

Co-authored-by: Marcel Ebert <mail@marcel-ebert.de>